name: Publish native build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  native:
    permissions:
      actions: read
      contents: read
      id-token: write
    uses: MyWallpapers/native-addon-toolchain/.github/workflows/native-addon-build.yml@f2b54c880ab98926151273f7bb4587d9f863630b
