name: Publish native build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  native:
    permissions:
      actions: read
      contents: read
      id-token: write
    uses: MyWallpapers/native-addon-toolchain/.github/workflows/native-addon-build.yml@836229c8189dbeff782e3e08087ae27e6630daa8
